<a href="https://colab.research.google.com/github/Jangbugyeong/Machine-Learning/blob/main/3%EC%A3%BC%EC%B0%A8_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
a=np.array([2,3,4])

In [ ]:
a

array([2, 3, 4])

In [ ]:
a[1]

np.int64(3)

In [ ]:
a1=np.array(5)

In [ ]:
a1

array(5)

In [ ]:
a1.shape

()

In [ ]:
a.shape

(3,)

In [ ]:
3+5

8

In [ ]:
'a'+'b'

'ab'

In [ ]:
storea=[20,10,30]
storeb=[70,90,70]

In [ ]:
storea+storeb

[20, 10, 30, 70, 90, 70]

In [ ]:
list_sum=storea+storeb

In [ ]:
list_sum

[20, 10, 30, 70, 90, 70]

In [ ]:
np_storea=np.array(storea)
np_storeb=np.array(storeb)

In [ ]:
array_sum=np_storea+np_storeb
array_sum

array([ 90, 100, 100])

In [ ]:
a.shape,a.ndim,a.itemsize,a.size

((3,), 1, 8, 3)

In [ ]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.ndim

2

In [ ]:
b.shape

(2, 3)

In [ ]:
a=np.array([10,20,30])
b=np.array([1,2,3])

In [ ]:
a+b


array([11, 22, 33])

In [ ]:
a*b

array([10, 40, 90])

In [ ]:
a-b

array([ 9, 18, 27])

In [ ]:
a/b

array([10., 10., 10.])

In [ ]:
a=np.array([10,20,30])
a*10

array([100, 200, 300])

In [ ]:
a+10

array([20, 30, 40])

In [ ]:
b=np.array([[10,20,30],[40,50,60]])
c=np.array([2,3,4])
b+c

array([[12, 23, 34],
       [42, 53, 64]])

In [ ]:
b*c

array([[ 20,  60, 120],
       [ 80, 150, 240]])

In [ ]:
b+3

array([[13, 23, 33],
       [43, 53, 63]])

NameError: name 'ones' is not defined

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((2,3),100)

array([[100, 100, 100],
       [100, 100, 100]])

In [ ]:
np.eye(4)*10

array([[10.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 10.]])

NameError: name 'arange' is not defined

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
a=np.logspace(0,5,6)

In [ ]:
a

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [ ]:
np.log10(a)

array([0., 1., 2., 3., 4., 5.])

In [ ]:
np.linspace(np.sin(0),np.sin(np.pi),10)

array([0.00000000e+00, 1.36071867e-17, 2.72143733e-17, 4.08215600e-17,
       5.44287466e-17, 6.80359333e-17, 8.16431199e-17, 9.52503066e-17,
       1.08857493e-16, 1.22464680e-16])

In [ ]:
b=np.array([[2,3,5]])
b.shape

(1, 3)

In [ ]:
c=np.array([[2],[3],[5]])
c

array([[2],
       [3],
       [5]])

In [ ]:
c.shape

(3, 1)

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[0,1,2]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]])

In [ ]:
print(a[0][0])

1


In [ ]:
print(a[2])

[7 8 9]


In [ ]:
a[1:][0:2]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9],[0,1,2]])
arr_2d[1:,0:2]

array([[4, 5],
       [7, 8],
       [0, 1]])

In [ ]:
a=np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
a[0]

array([1, 2, 3, 4])

In [ ]:
a[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
a[1:,2]

array([ 7, 11, 15])

In [ ]:
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [ ]:
a[::2,::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [ ]:
a[:,2]

array([ 3,  7, 11, 15])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
a%2==0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [ ]:
a%2==1

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [ ]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
a[a%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [ ]:
a=np.array([10,20,30])
a.max(),a.min()

(np.int64(30), np.int64(10))

In [ ]:
a.mean()

np.float64(20.0)

In [ ]:
a.astype(np.float64)

array([10., 20., 30.])

In [ ]:
b=np.array([[1,1],[2,2],[3,3],[4,4]])

In [ ]:
b

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
b.flatten()

array([1, 1, 2, 2, 3, 3, 4, 4])

In [ ]:
b.T

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
c=np.array([35,24,55,69,19,99])
c.sort()
c[::-1]

array([99, 69, 55, 35, 24, 19])

In [ ]:
d=np.array([[35,24,55],[69,19,9],[4,1,11]])
d

array([[35, 24, 55],
       [69, 19,  9],
       [ 4,  1, 11]])

In [ ]:
d.sort()
d

array([[24, 35, 55],
       [ 9, 19, 69],
       [ 1,  4, 11]])

In [ ]:
d=np.array([[35,24,55],[69,19,9],[4,1,11]])
d


array([[35, 24, 55],
       [69, 19,  9],
       [ 4,  1, 11]])

In [ ]:
d.sort(axis=0)
d

array([[ 4,  1,  9],
       [35, 19, 11],
       [69, 24, 55]])

In [ ]:
y=np.arange(0,20)
y


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
y.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
y.reshape(10,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [ ]:
arr=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

In [ ]:
print(np.sum(arr,axis=0))

[ 5 10 15 20 25]


In [ ]:
print(np.sum(arr,axis=1))

[15 15 15 15 15]


In [ ]:
print(np.sum(arr,axis=(0,1)))

75
