<a href="https://colab.research.google.com/github/Jangbugyeong/Machine-Learning/blob/main/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%202%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello,world")

hello,world


In [ ]:
print("hello,world")

hello,world


In [ ]:
print("welcome to data science and machine learning")

welcome to data science and machine learning


In [ ]:
animals = ['lion','cat','tiger','dog']
animals.sort()
animals

['cat', 'dog', 'lion', 'tiger']

In [ ]:
animals.append('rabbit')
animals

['cat', 'dog', 'lion', 'tiger', 'rabbit']

In [ ]:
animals.reverse

<function list.reverse()>

In [ ]:
animals.reverse()
animals

['rabbit', 'tiger', 'lion', 'dog', 'cat']

In [ ]:
import math

In [ ]:
a=math.fabs(-10)
print('math.fabs(-10):',a)
b=math.sin(math.pi/2.0)
print('math.sin(m.pi/2.0):',b)

math.fabs(-10): 10.0
math.sin(m.pi/2.0): 1.0


In [ ]:
import random

In [ ]:
random.randrange(1,7)

3

In [ ]:
num=100


In [ ]:
num=num+100
print(num)

200


In [ ]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
a[1]

2

In [ ]:
store_a=[20,10,30]
store_b=[70,90,70]

In [ ]:
list_sum=store_a+store_b
list_sum

[20, 10, 30, 70, 90, 70]

In [ ]:
np_store_a=np.array(store_a)
np_store_b=np.array(store_b)
array_sum=np_store_a+np_store_b
array_sum

array([ 90, 100, 100])

In [ ]:
a= np.array([2,3,4])
a.shape,a.ndim,a.dtype,a.itemsize,a.size

((3,), 1, dtype('int64'), 8, 3)

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b.shape

(2, 3)

In [ ]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
a + b

array([11, 22, 33])

In [ ]:
a-b

array([ 9, 18, 27])

In [ ]:
a*b

array([10, 40, 90])

In [ ]:
a/b

array([10., 10., 10.])