In [ ]:
import numpy as np


In [ ]:
np.arange(1,46)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [4]:
import random

In [5]:
random.seed(85)

In [6]:
lotto=[22, 9, 15, 44, 37, 39]

In [7]:
random.shuffle(lotto)

In [8]:
lotto

[15, 44, 39, 22, 37, 9]

In [9]:
lotto.sort(
)

In [10]:
lotto

[9, 15, 22, 37, 39, 44]

In [11]:
lotto.append(2)

In [12]:
lotto

[9, 15, 22, 37, 39, 44, 2]

In [14]:
n_arr=np.arange(25).reshape(5,5)

In [15]:
n_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
print(n_arr[0][0])

0


In [22]:
print(n_arr[-1][-1])

24


In [24]:
n_arr[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
n_arr[0: ,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [30]:
n_arr[0:2].reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [32]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [33]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [34]:
a[:,1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [35]:
a[0:1,0:2]

array([[1, 2]])

In [36]:
a[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

In [38]:
b=np.arange(1,26).reshape(5,5)

In [39]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
row_sums = np.sum(b, axis=1)

In [41]:
print(row_sums)

[ 15  40  65  90 115]


In [42]:
sums=np.sum(b,axis=0)
print(sums)

[55 60 65 70 75]
